### ISSUE TITLE
Failure when /run/user does not exist

### ISSUE THREAD

**Issue by maringuu** [ifreund/xdg-runtime-dir#2]
I'm not sure if this is intended but if `/run/user/` does not exist the deamon will fail due to `error.FileNotFound`.

I don't know who should create this directory through. Maybe it should exist and this is a bug on my system.

**Comment by ifreund** [comment]
Hmm, I don't think creating it if needed would hurt. We should probably expose the `rundir_parent` and `socket_path` constants in the build.zig as build options and add documentation to make it more transparent what paths will be used as well.

**Comment by maringuu** [comment]
Good idea. If you aren't faster than me I'll probably implement this tomorrow.
